### ISSUE TITLE
S3 store use throws Exception in thread "main" retrofit.RetrofitError: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by NutterzUK** [devinrsmith/kraken-java#1]
Hi,

If I set an s3 store, I seem to get this exception:
Exception in thread "main" retrofit.RetrofitError: 422 Unprocessable Entity
    at retrofit.RetrofitError.httpError(RetrofitError.java:40)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at com.sun.proxy.$Proxy0.uploadImage(Unknown Source)
    at com.devinrsmith.kraken.KrakenIOExampleMain.main(KrakenIOExampleMain.java:58)

It doesn't seem to describe what the issue is. Any help would be appreciated.
Thanks,

**Comment by devinrsmith** [comment]
Hi @NutterzUK. This is a sample application, I'm not maintaining it at all. It may be the case that kraken changed their API, or there might be some issue with the code. Good luck.

**Comment by NutterzUK** [comment]
Hi.

Thanks for the reply. Kraken link to this repo from their docs here: https://kraken.io/docs/getting-started.

I've mentioned it to them, perhaps they can take a look or create an official library. I wasn't aware this was not maintained by them since it's linked in the left nav and looks like it's part of krakens api :).

Thanks,
Steve
